### ISSUE TITLE
Missing collections

### ISSUE THREAD

**Issue by mslinn** [mslinn/scala-collections-charts#1]
Missing:

  * new [SeqMap](https://scala-lang.org/api/current/scala/collection/SeqMap.html) trait, implemented by [VectorMap](https://scala-lang.org/api/current/scala/collection/immutable/VectorMap.html) and [TreeSeqMap](https://scala-lang.org/api/current/scala/collection/immutable/TreeSeqMap.html)
  * [ArrayDeque](https://www.scala-lang.org/api/current/scala/collection/mutable/ArrayDeque.html

**Comment by mslinn** [comment]
I updated the definitions to include the missing collections. 

I have not figured out how to show multiple inheritance using the [DOT graph description language](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) used by Graphviz (although it seems possible), so I arbitrarily decided how to categorize some collections. 

I also moved some nodes around because they made more sense to me in the new locations. This had the effect of flattening out the hierarchy, increasing the width of the diagrams and decreasing the height.

Feedback and discussion is welcomed, I do not claim to be the final authority on this.

## scala collection immutable
![scala collection immutable](https://user-images.githubusercontent.com/485818/60041531-80a03f80-9670-11e9-804e-104d01f59da8.png)

## scala collection mutable
![scala collection mutable](https://user-images.githubusercontent.com/485818/60041533-8138d600-9670-11e9-9d23-3fc45f06c321.png)

## scala collection
![scala collection](https://user-images.githubusercontent.com/485818/60041534-8138d600-9670-11e9-8114-615d14f83234.png)

## legend
![legend](https://user-images.githubusercontent.com/485818/60041535-8138d600-9670-11e9-8d79-b977e54b8b51.png)

**Comment by joshlemer** [comment]
* immutable.ListMap extends immutable.SeqMap
* mutable.LinkedHashMap extends mutable.SeqMap
* mutable.ArrayDeque extends both mutable.IndexedBuffer and mutable.IndexedSeq

**Comment by mslinn** [comment]
Hmm, I put them in the `.gv` file, but they didn't show up... must have missed something... thanks!

**Comment by mslinn** [comment]
One more time...

## scala collection immutable
![scala collection immutable](https://user-images.githubusercontent.com/485818/60043725-96fcca00-9675-11e9-93b7-6fdc2dfb42f7.png)

## scala collection mutable
![scala collection mutable](https://user-images.githubusercontent.com/485818/60043726-96fcca00-9675-11e9-9ce5-590c15560cd2.png)

**Comment by mslinn** [comment]
I've modified the diagrams again. No point in continuing to post every image when they are so easy to generate.

**Comment by er1c** [comment]
in the mutable diagram, Iterable is missing a link to Seq

**Comment by mslinn** [comment]
Up-to-date diagrams are available to [ScalaCourses](https://www.ScalaCourses.com) students. As I mentioned June 24, 2019 above I don't maintain the rendered diagrams here, just the source. Anyone can regenerate the diagrams themselves from the source any time.
